### ISSUE TITLE
Making this usable in the browser?

### ISSUE THREAD

**Issue by valadaptive** [cto-af/unicode-trie#11]
I stumbled upon your linebreak fork and want to use it in a Web project, but it seems like this package has a couple Node-isms: the use of `Buffer` and `zlib`.

Removing `Buffer` shouldn't be that big of an issue--since a `Buffer` is a subclass of `Uint8Array`, we can just treat it as one and use all the relevant APIs there.

`zlib` usage might be a bigger challenge--the original version of this package used `tiny-inflate`, and it seems like `fflate` might be the best alternative.

This would, of course, add a bit to the bundle size when using the package natively, but a lot of Unicode stuff is really valuable client-side (like text wrapping).

**Comment by hildjj** [comment]
For reference, Intl.Segmenter is close on Firefox, finally: https://bugzilla.mozilla.org/show_bug.cgi?id=1883914

That does NOT block this work.

**Comment by valadaptive** [comment]
4 hours ago, wow! I'm literally *just now* working on a feature that requires Intl.Segmenter.

As I understand it, `Intl.Segmenter` doesn't replace things like `linebreak`--word boundaries aren't the same as line break opportunities.

**Comment by hildjj** [comment]
Correct.  @cto.af/string-width and therefore @cto.af/linewrap use `new Intl.Segmenter({ granularity: 'grapheme'}` in a way that could be replaced if needed, but would be tedious.

**Comment by hildjj** [comment]
I released most of the cluster last night with this update, before the TypeScript 5.4 release started messing with my dependencies:
- @cto.af/unicode-trie@2.0.0
- @cto.af/linebreak@2.0.0
- @cto.af/string-width@3.0.0
- @cto.af/linewrap@2.0.0
- @cto.af/linewrap-cli@2.0.0

Still in progress:
- minus-h
- basura
- expat-wasm-dom

Thank you very much @valadaptive for the bug report and the code!
